module.exports = [
{
  title: 'Project 1, what I learned, and plans for Project 2',
  url: '/project-1-what-i-learned-plans-project-2',
  publishDate: '2022-09-30',
  logoSrc: '',
  logoAlt: '',
  tags: ['saas', '3-projects-in-3-months', 'yet-another-link-shortener'],
},
{
  title: 'YALS technology choices and system layout',
  url: '/yals-technology-choices-and-system-layout',
  publishDate: '2022-09-06',
  logoSrc: '',
  logoAlt: '',
  tags: ['saas', '3-projects-in-3-months', 'yet-another-link-shortener'],
},
,{
  title: 'First Project: Yet Another Link Shortener!',
  url: '/first-project-yet-another-link-shortener',
  publishDate: '2022-09-06',
  logoSrc: '',
  logoAlt: '',
  tags: ['saas', '3-projects-in-3-months', 'yet-another-link-shortener'],
},
{
  title: '3 projects in 3 months',
  url: '/3-projects-in-3-months',
  publishDate: '2022-09-03',
  logoSrc: '',
  logoAlt: '',
  tags: ['saas'],
},
,{
  title: 'Writing Comments in Javascript and other languages',
  url: '/writing-comments-in-javascript-and-other-languages',
  publishDate: '2020-03-31',
  logoSrc: '',
  logoAlt: '',
  tags: ['intro to programming', 'comments', 'javascript', 'ruby', 'python', 'c', 'c++'],
},
,{
  title: 'Coding Challenge: Maximum Pairwise Product',
  url: '/coding-challenge-maximum-pairwise-product',
  publishDate: '2019-12-19',
  logoSrc: '',
  logoAlt: '',
  tags: ['coding-challenge', 'algorithms'],
},
]
